winget install -id Git.Git
winget install -id CPUID.CPU-Z
winget install -id 7zip.7zip
winget install -id GitHub.GitHubDesktop
winget install -id jqlang.jq
winget install -id junegunn.fzf
winget install -id sharkdp.bat
winget install -id JanDeDobbeleer.OhMyPosh
winget install -id OBSProject.OBSStudio
winget install -id charmbracelet.gum
